In [1]:
import numpy as np

In [2]:
np.random.seed(322)

In [3]:
n = np.arange(1, 21)

In [4]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
print(np.random.choice(a=n, size=20, replace=True))

[ 1 10  9  6 20 16 13  7 18  4 18 14  6 14 15 18  4  2  2  6]


In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets

%matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['font.size'] = 14
plt.style.use("fivethirtyeight")

In [7]:
iris = datasets.load_iris()

In [8]:
data = pd.DataFrame(iris.data, columns = iris.feature_names)
data['species'] = pd.Series(iris.target)
target_names = iris.target_names

In [36]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree

In [45]:
data = data.sample(frac=1)

In [46]:
x = data.drop(labels=['species'], axis=1)
y = data['species']
X = StandardScaler().fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=322)

In [40]:
np.random.seed(322)

In [41]:
samples = [np.random.choice(a=len(X_train), size=len(X_train), replace=True) for _ in range(1, 11)]

In [14]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
116                6.5               3.0                5.5               1.8   
141                6.9               3.1                5.1               2.3   
45                 4.8               3.0                1.4               0.3   
118                7.7               2.6                6.9               2.3   
64                 5.6               2.9                3.6               1.3   

     species  
116        2  
141        2  
45         0  
118        2  
64         1

In [15]:
dtc = DecisionTreeClassifier(random_state=322)

In [21]:
scores = []
for sample in samples:
    xtrain = data.iloc[sample, :-1]
    ytrain = data.iloc[sample]['species']
    dtc.fit(xtrain, ytrain)
    #y_pred = dtc.predict(X_test)
    #print(y_pred)
    scores.append(dtc.score(X_test, y_test))

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rfc = RandomForestClassifier(n_estimators = 1000, random_state=322)
rfc.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=322)

In [48]:
rfc.score(X_test, y_test)

0.9111111111111111

In [49]:
for row in X_test:
    yhat = rfc.predict(row.reshape(1, -1))
    print('Predicted class: %d' % yhat[0])

Predicted class: 0
Predicted class: 1
Predicted class: 2
Predicted class: 2
Predicted class: 1
Predicted class: 1
Predicted class: 1
Predicted class: 1
Predicted class: 1
Predicted class: 2
Predicted class: 2
Predicted class: 2
Predicted class: 1
Predicted class: 2
Predicted class: 0
Predicted class: 2
Predicted class: 0
Predicted class: 2
Predicted class: 0
Predicted class: 2
Predicted class: 1
Predicted class: 2
Predicted class: 0
Predicted class: 0
Predicted class: 1
Predicted class: 1
Predicted class: 1
Predicted class: 0
Predicted class: 1
Predicted class: 1
Predicted class: 0
Predicted class: 0
Predicted class: 0
Predicted class: 0
Predicted class: 1
Predicted class: 0
Predicted class: 2
Predicted class: 2
Predicted class: 2
Predicted class: 2
Predicted class: 2
Predicted class: 2
Predicted class: 0
Predicted class: 1
Predicted class: 2


In [50]:
data.columns[:-1]

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [51]:
rfc.feature_importances_

array([0.08978655, 0.01928314, 0.44843152, 0.44249879])